name: Deploy React App

on:
  push:
    branches:
      - main  # Замените на ветку, которую хотите использовать

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка sshpass
      - name: Install sshpass
        run: sudo apt-get install sshpass

      # 3. Сборка Docker-образа локально
      - name: Build Docker image
        run: |
          docker build -t react-app .

      # 4. Копирование docker-compose.yml на сервер
      - name: Copy docker-compose.yml to server
        run: |
          sshpass -p "${{ secrets.PASSWORD_VDS }}" scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.USER_VDS }}@${{ secrets.IP_VDS }}:/root/apps/Frontend

      # 5. Копирование Docker-образа на сервер
      - name: Copy Docker image to server
        run: |
          docker save react-app | sshpass -p "${{ secrets.PASSWORD_VDS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USER_VDS }}@${{ secrets.IP_VDS }} "docker load"

      # 6. Деплой на сервер
      - name: Deploy to server
        run: |
          sshpass -p "${{ secrets.PASSWORD_VDS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USER_VDS }}@${{ secrets.IP_VDS }} "cd /root/apps/Frontend && docker-compose down && docker-compose up -d"
